# Запуск PHP CS Fixer для проверки стиля кода на соответствие стандартам

name: Codestyle
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    name: Codestyle checker
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: zip

      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install

      - name: Run PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run
